config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users

  resources :pitch_decks, only: %i[new create show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pitch_deck.rb
# frozen_string_literal: true

class PitchDeck < ApplicationRecord
  belongs_to :user
  has_one_attached :document
  has_many_attached :images

  enum image_process: {
    open: 0,
    inprogress: 1,
    finished: 2
  }

  delegate :email, to: :user, prefix: true

  validates :title, presence: true, length: { maximum: 200 }
  validates :document, presence: true

  after_create :split_images_from_document

  scope :newest, -> { order('id DESC') }

  private

  def split_images_from_document
    SplitPitchDeckDocumentWorker.perform_at(20.seconds.from_now, id)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pitch_decks, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :load_resources

  def index; end

  private

  def load_resources
    @pitch_decks ||= current_user.pitch_decks.newest.includes(images_attachments: :blob)
  end
end

app/controllers/pitch_decks_controller.rb
# frozen_string_literal: true

class PitchDecksController < ApplicationController
  before_action :load_resource, only: :show

  def show
  end

  def new
    @pitch_deck ||= current_user.pitch_decks.new
  end

  def create
    @pitch_deck = current_user.pitch_decks.build(permit_params)
    if @pitch_deck.save
      flash[:success] = I18n.t('controllers.pitch_decks.create.success')
      redirect_to root_path
    else
      flash[:danger] = @pitch_deck.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def permit_params
    params.require(:pitch_deck).permit(:title, :document)
  end

  def load_resource
    @pitch_deck ||= current_user.pitch_decks.find_by(id: params[:id])
    return if @pitch_deck
    flash[:danger] = "Pitch deck not found!"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pitch_deck_helper.rb
module PitchDeckHelper
  def image_process_class pitch_deck
    case
    when pitch_deck.inprogress?
      "label-warning"
    when pitch_deck.finished?
      "label-success"
    else
      "label-info"
    end
  end
end

app/views/home/index.html.erb
<h1>Pitch Decks</h1>

<div class="row">
  <%= link_to "Create new pitch deck", new_pitch_deck_path, class: "btn btn-primary" %>

  <span style="color: red">
    Auto refresh in <span id="countdown">30</span>s
  </span>
</div>

<br />

<% if @pitch_decks.any? %>
  <ul class="list-group list-group-flush" id="pitch-decks-list">
    <% @pitch_decks.each do |pitch_deck| %>
      <li class="list-group-item">
        <% if pitch_deck.finished? %>
          <%= link_to pitch_deck_path(pitch_deck) do %>
            <%= pitch_deck.title %>
          <% end %>
        <% else %>
          <%= pitch_deck.title %>
        <% end %>
        <span class="label <%= image_process_class(pitch_deck) %>"  style="float: right;"><%= pitch_deck.image_process %></span>
      </li>
    <% end %>
  </ul>
<% else %>
  There aren't any pitch deck.
  You can create a pitch deck <%= link_to "here", new_pitch_deck_path %>
<% end %>

<script>
  var timeleft = 30;
  var downloadTimer = setInterval(function(){
    if(timeleft <= 0){
      clearInterval(downloadTimer);
      window.location.reload(true);
    }
    document.getElementById("countdown").innerHTML = timeleft;
    timeleft -= 1;
  }, 1000);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wefund</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <ul class="nav navbar-nav navbar-left">
        <%= link_to "Wefund", root_path, id: "logo", style: "padding-left: 40px" %>
      </ul>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, style: "padding-right: 40px" %></li>
        </ul>
      <% end %>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pitch_decks/new.html.erb
<h1>Create a new Pitch Deck</h1>

<%= form_for @pitch_deck do |f| %>
  <div class='form-group'>
    <%= f.label :title, class: 'form-label' %><br />
    <%= f.text_field :title, autofocus: true, autocomplete: 'title', class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :document, class: 'form-label' %><br />
    <%= f.file_field :document, accept: 'application/pdf', class: 'form-control' %>
  </div>

  <div class='center'>
    <%= f.submit 'Submit', class: 'btn btn-lg btn-primary' %>
    <%= link_to 'Cancel', root_path, class: 'btn btn-lg btn-default' %>
  </div>
<% end %>

app/views/pitch_decks/show.html.erb
<div class="row center">
  <h2><%= @pitch_deck.title %></h2>

  <hr />

  <% @pitch_deck.images.each do |img| %>
    <figure>
      <%= image_tag img %>
    </figure>
    <br />
  <% end %>
</div>